### ISSUE TITLE
что то много конфигов надо фиксить

### ISSUE THREAD

**Issue by L09k0** [rogender/ag-configs#2]

**Comment by keyboardcrash1** [comment]
да нормально конфигов че ты

**Comment by L09k0** [comment]
Уважаемый игрок ваш конфиг был замечен чит у вас есть 5 мин что бы скинуть его и пройти проверку!

**Comment by keyboardcrash1** [comment]
ээээ чоооо

**Comment by anewnick** [comment]
**лучшие!**
